version: '3'

services:
  symfony :
    container_name: symfony
    build: ./app
    ports:
      - 80:80
      
  mysql:
    container_name: db
    image: mysql:latest
    restart: always
    ports:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
    volumes:
      - database_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'
  
  mailer:
    container_name: mailer
    image: schickling/mailcatcher
    ports: ["1025", "1080"]

volumes:
  database_data:
