version: '3'

services:
  symfony :
    container_name: app
    build: ./
    ports:
      - 80:80
      
  mysql:
    container_name: db
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
    volumes:
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - database_data:/var/lib/mysql
      # - ./docker/db/data:/var/lib/sql/data:rw

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9000:80
  
  mailer:
    container_name: mailer
    image: schickling/mailcatcher
    ports: ["1025", "1080"]

volumes:
  database_data:
