version: '3'

services:
  database:
    container_name: database
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: motdepasse
      MYSQL_ALLOW_EMPTY_PASSWORD: no
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: symfony
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - database
    networks:
      - mynetwork
    environment:
      PMA_HOST: database
  
  mailer:
    container_name: mailer
    image: schickling/mailcatcher
    ports: ["1025", "1080"]

  symfony :
    container_name: symfony
    build: ./app
    ports:
      - 80:80
    depends_on:
      - database
    networks:
      - mynetwork

volumes:
  database_data:

networks:
  mynetwork: